### ISSUE TITLE
Possible to use boolean/binary data from the start?

### ISSUE THREAD

**Issue by rcalfredson** [isarlab-department-engineering/WS-COUNT#1]
Hello! Is it accurate that the ground-truth data can consist of ones and zeros directly, as opposed to the actual number of objects in each image? Such is my inference from studying lines 149-153 of the file [fruit_count_dataset.py](https://github.com/isarlab-department-engineering/WS-COUNT/blob/0b12b610ad80d66d6a654c1d96163fa85816c597/dataset/fruit_count_dataset.py#L149), but in the paper I read "our approach needs only the fruit instance counts in the image," which suggests actual numbers may be needed. Thank you very much.

**Comment by enricobellocchio** [comment]
Hello! thank you for your interest on our project!
of course you can collect a ground truth consisting of only 0 and 1 as a boolean/binary label if you think to do the training process on the Presence/Absence Classifier and on the WSCOUNT Model. The number of objects is reported on our datasets for testing the performances for the counting task and for training the SCOUNT baseline.
Thank you again and sorry for the delay for the answer.
Best Regards,
Enrico.
